[package]
name = "sandbox_hooks"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
shared = { path = "../shared" }
minhook-detours = { git = "https://github.com/amrbashir/minhook-detours-rs" }
windows = { workspace = true }
